pruner:
  type: hyperband # or median
  # These are for hyperband pruner
  min_resource: 1
  max_resource: 120
  reduction_factor: 3
  # These are for median pruner
  n_startup_trials: 5
  n_warmup_steps: 10
  interval_steps: 1

tuner:
  n_trials: 50
  lr_low: 1e-5
  lr_high: 1e-2
  weight_decay_low: 1e-6
  weight_decay_high: 1e-2
